### ISSUE TITLE
Sound off by default and other requests

### ISSUE THREAD

**Issue by mindware** [yoshiori/pomodoro#4]
I think these would greatly improve this plugin:

1. We need sound to be off by default, it is incredibly distracting. I tried adding a "'pomodoro.playSounds' : false" to config, but it did not work. 

2. This pomodoro tool could evolve into something much more useful. By simply storing the pomodoros history, this tool could be a very powerful. A way to keep track of how many pomodoros would give us great insights, such as: how long it took to do x feature, your progress and the time spent in x feature of x project for  x client. 

3. Working keybinds.

**Comment by aleksandar-todorovic** [comment]
Could you share a keyboard combination that you think is appropriate for the job?

Both `Ctrl+Shift+P` and `Ctrl+Alt+P` are already mapped inside Atom. I have no other ideas, but I could easily create working keybinds and submit it as a pull request.

As for the first issue, I _think_ it is resolved now by default?
